# Generated by Django 5.1.7 on 2025-05-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizattempt_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='marking_key',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
