# Generated by Django 5.2 on 2025-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
